### ISSUE TITLE
Error messages for unmatched ehrQL outputs could be more helpful

### ISSUE THREAD

**Issue by evansd** [opensafely-core/pipeline#384]
Given the follow snippet of a `project.yaml` file:
```yaml
extract:
  run: ehrql:v1 generate-dataset analysis/dataset_definition_varying.py
    --output output/extracts:arrow
  outputs:
    highly_sensitive:
      cohort: output/extracts*.arrow
```

The pipeline library reject it with the error:
```
--output in run command and outputs must match
```

The correct output specification should in fact be `output/extracts/*.arrow` (i.e. with a directory separator before the glob) but that's not obvious and the error message doesn't help.

Rather than relaxing the constraints here I think we should just try to make the error more helpful. I think we ought to be able to give the exact output pattern we were expecting. So something like:
```
output specification must match the `--output` argument in the `run` command
              got: output/extracts*.arrow
but was expecting: output/extracts/*.arrow
```

Related Slack thread:
https://bennettoxford.slack.com/archives/C07UG9PCR6E/p1743163222695719?thread_ts=1742420829.376949&cid=C07UG9PCR6E
